### ISSUE TITLE
Support "moduleResolution": "bundler" in tsconfig.json

### ISSUE THREAD

**Issue by anisabboud** [FirebaseExtended/rxfire#106]
[Angular v18](https://github.com/angular/angular-cli/commit/f452589e2c921448b76a138a5f34ba92ad05e297) now uses `"moduleResolution": "bundler"` (instead of `"moduleResolution": "node"`) in `tsconfig.json`.

That causes compilation errors in AngularFire, which relies on rxfire.

See https://github.com/angular/angularfire/issues/3541#issuecomment-2139600513 and https://github.com/FirebaseExtended/rxfire/issues/100#issuecomment-2140857573.

**Comment by ludoviccyril** [comment]
Any news on this?

**Comment by jamesdaniels** [comment]
Should be addressed in v6.1
