### ISSUE TITLE
Please release 6.0.6

### ISSUE THREAD

**Issue by ebeloded** [FirebaseExtended/rxfire#108]
The fix that fixes types was merged 5 months ago and the version in the repo has been bumped. Please release the updated version.

**Comment by emmerich** [comment]
@davideast Any chance we can get 6.0.6 out the door? Happy to contribute!

**Comment by ludoviccyril** [comment]
This package is dead. The Angular Fire team should switch to another dependency.

**Comment by KariNarhi28** [comment]
Either the project is dead and abandoned or @davideast is on a damn long vacation.

Really hope for that 6.0.6 release or AngularFire team switching to something else.

**Comment by mazeneko** [comment]
I look forward to type-safe programming!🙌

**Comment by BenjaminAfrolabs** [comment]
It looks like an attempt was made by @jamesdaniels a couple of weeks ago, but the workflow failed since it uses a deprecated version of `actions/upload-artifact`

**Comment by jamesdaniels** [comment]
Just released v6.1 after patching the CI/CD and bumping to v11
