### ISSUE TITLE
Why are dependencies marked as external?

### ISSUE THREAD

**Issue by jhuleatt** [FirebaseExtended/rxfire#14]
Why are `dependencies` marked as `external` in the rollup config? Shouldn't only `peerDependencies` be `external`?

https://github.com/FirebaseExtended/rxfire/blob/4370987eedee79941238033bdeef45d117a55264/rollup.config.js#L43-L46

Right now, tslib is the only dependency. Should we make that a `devDependency`?

**Comment by jamesdaniels** [comment]
@jhuleatt `tslib` needs to be a dependency, just how it works. Externals here matter for the CJS builds, otherwise it would bundle tslib, etc.
