### ISSUE TITLE
Are we exporting ESM where we should be exporting CJS?

### ISSUE THREAD

**Issue by jhuleatt** [FirebaseExtended/rxfire#17]
Building NextJS on Node 12 results in the following error:

```
import { Observable, from, of } from 'rxjs';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by galvarez421** [comment]
I have encountered this issue using Next.js and reactfire after upgrading from reactfire 3.0.0-rc.0 to 3.0.0-rc.1. In case it's useful to know, I encountered this on both Node v14 and Node v16. Reverting back to reactfire 3.0.0-rc.0 seems to fix the issue for now.

**Comment by jhuleatt** [comment]
@galvarez421 thanks for the report! I had assumed that Node 14/16's support for ESM would solve this, so looks like we definitely need to investigate
