### ISSUE TITLE
duplicate imports in the doc() documentation

### ISSUE THREAD

**Issue by davie-robertson** [FirebaseExtended/rxfire#57]
https://github.com/FirebaseExtended/rxfire/blob/main/docs/firestore.md#doc

doc is being imported from both rxfire and firebase so code won't run

```
  import { **doc** } from 'rxfire/firestore';
  import { initializeApp } from 'firebase/app';
  import { getFirestore, **doc**, setDoc } from 'firebase/firestore';
```

**Comment by julienreszka** [comment]
Did you mitigate this if so how did you do it?

**Comment by davideast** [comment]
Right now we recommend using the `as` syntax to rewrite an import. We'll revisit the API in the next release to avoid collisions.

```ts
 import { doc as doc$ } from 'rxfire/firestore';
 import { initializeApp } from 'firebase/app';
 import { getFirestore, **doc**, setDoc } from 'firebase/firestore';
```
