### ISSUE TITLE
bug: database `list` and `listVal` does not receive updates if query is initially empty

### ISSUE THREAD

**Issue by ippeiukai** [FirebaseExtended/rxfire#70]
## Description

Subscribing to `list(query)` when that query (ref) is empty emits only one event with empty array value and does not emit subsequent updates of that query (ref).

## Cause

When `query` result is empty, `!change.snapshot.exists()` is true and switchMap returns at l.56, never reaching l.60 where observing for subsequent events starts.

https://github.com/FirebaseExtended/rxfire/blob/95ffa992e64fe97187ed11d9f775d97e8c3f9567/database/list/index.ts#L53-L60

**Comment by ippeiukai** [comment]
https://github.com/angular/angularfire/issues/3254

**Comment by tdcolvin** [comment]
Same problem here, which is also affecting AngularFire further on up the tree (https://github.com/angular/angularfire/issues/3254)

**Comment by davideast** [comment]
This has been fixed with #79 and we're working on updating it in AngularFire as well. You can test this in the canary version right now: `npm i rxfire@canary`.
