### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by paslavsky** [FirebaseExtended/rxfire#71]
Hi @jamesdaniels, @Feiyang1, @hsubox76, @davideast,

I want to bump into a conversation about the future of this repository. I tagged you as top contributors. 
There have been no activities since the end of 2020, and it's sad 😭.

**Comment by davideast** [comment]
Hey @paslavsky! It's not dead. It's been stable for awhile although that has changed with lots of updates. I'll be working on getting it up to date with the latest RxJS so hang tight.
