### ISSUE TITLE
Proposal: Add Firestore Count Observable

### ISSUE THREAD

**Issue by davideast** [FirebaseExtended/rxfire#72]
> tl;dr - Add observable support for the `getCountFromServer()` and `getCount()` functions in both `firebase/firestore` and `firebase/firestore/lite`.

While it's fairly straightforward to wrap the `getCountFromServer()` function into an observable, it's an extra step that most people will be taking in their code. This proposal recommends adding an observable support to make the function easy to import and idiomatic with RxJS code. This will also allow better support in AngularFire which Zone wraps the majority of functions exported from RxFire.

### Example API

```ts
import { collectionCount$, collectionCountSnap$ } from 'rxfire/firestore';
// Also available in firestore/lite
import { collectionCount$, collectionCountSnap$ } from 'rxfire/firestore/lite';
import { getFirestore, collection } from 'firebase/firestore';

const db = getFirestore();
const likesCol = collection(db, 'posts/post_id_123/likes');

// One version with the snapshot
countSnap$(likesCol).subscribe(snapshot => {
  console.log(snapshot.data().count);
})

// One version with just the number
collectionCount$(likesCol).subscribe(count => {
   console.log(count);
})
```

### Why the $?
The `$` has been common in RxJS and Angular codebases for awhile (at least I think, I might be getting old). This allows us to visually show that this function returns an observable and allows us not to collide with any of the Firebase JS SDK names as well. Currently there are a number of function collections such as `doc()`, `collection()`, and others. Eventually we could rename them to use `doc$()`, `collection$()`, and so on. I would love to hear people's thoughts as this is merely a suggestion.

**Comment by jhuleatt** [comment]
Overall, yes, this sounds worthwhile! One idea:

Since `getCountFromServer` is a one-time fetch, instead of a subscription, would it be worth providing an additional observable that re-fetches the count at some interval, maybe with an api similar to [`timer`](https://www.learnrxjs.io/learn-rxjs/operators/creation/timer)? 

```js
import { collectionCountListen$ } from 'rxfire/firestore';

// refresh the count value every 5 minutes
collectionCountListen$(
  likesCol,
  // refresh every 5 minutes
  5 * 1000 * 60
).subscribe(() => {
  /* ... */
});
```

The downside would definitely be that it incurs extra reads.

**Comment by jhuleatt** [comment]
Or, add a code sample to the docs showing how to do this. I _think_ it would look like:

```js
import { repeat } from 'rxjs';

import { collectionCount$} from 'rxfire/firestore';
import { getFirestore, collection } from 'firebase/firestore';

const db = getFirestore();
const likesCol = collection(db, 'posts/post_id_123/likes');

countSnap$(likesCol)
  .pipe(
    // re-fetch every 30 seconds.
    // Stop fetching after 100 re-fetches so we don't do too many reads
    repeat({ count: 100, delay: 30 * 1000 }),
  )
  .subscribe((count) => {
    console.log(count);
  });
```
